### ISSUE TITLE
reflection about meeting 30/08

### ISSUE THREAD

**Issue by OlegMakeienko** [PinMeTo-Project-to-Local-Landing-Page/Local-landing-pages#5]

**Comment by Waspk** [comment]
Core Technology:
WordPress appears to be the primary platform, as mentioned in several search results.
 
Bulk Page Generation Tool:
LPagery is prominently featured in the search results. It's a WordPress plugin specifically designed for bulk local landing page generation.
 
Page Builder:
The solution should be compatible with popular page builders. Elementor and Divi are mentioned in the search results.
 
Data Input:
CSV or XLSX files for inputting location data
Google Sheets integration (mentioned as a pro feature in LPagery)
 
SEO Optimisation:
The solution should include features for local SEO optimization, such as customizable meta tags, schema markup, and URL structure.
 
CRM Integration:
You mentioned seamless integration with existing CRM. Specific CRM systems aren't mentioned in the search results, so you'll need to ensure compatibility with your current CRM.
 
Analytics & Reporting:
While specific analytics tools aren't mentioned, integration with popular analytics platforms like Google Analytics would be beneficial.
 
Additional Features:
Radius-based page generation
Dynamic content generation (using placeholders)
Bulk update capabilities
Custom URI editor
Dynamic images
Interlinking between pages
 
Hosting and Performance:
Consider using a robust hosting solution that can handle multiple landing pages efficiently.

**Comment by Waspk** [comment]
1- what should we use angular or nod.js   
 2-We should use Google Maps or Map box if they are saying Map box then we should ask for the credentials
 3-What is the exact requirement of multi-landing pages or what is the requirement of different locations
