### ISSUE TITLE
Figma Design inputs

### ISSUE THREAD

**Issue by Waspk** [PinMeTo-Project-to-Local-Landing-Page/Local-landing-pages#6]
> Hello Guys 
> everyone will try to put his/her insights on the project design in Figma and will discuss it on Monday 

 _Originally posted by @Waspk in [#4](https://github.com/PinMeTo-Project-to-Local-Landing-Page/Local-landing-pages/issues/4#issuecomment-2320752578)_

**Comment by OlegMakeienko** [comment]
it´s done
